Ignore quality gate when threshold is zero.
jenkinsci/warnings-ng-plugin pull request #1367
Opened 2022-09-27 19:20 UTC by miked-rr

Add test to check success when quality gate threshold set to zero, update QualityGateEvaluator to not run evaluation when threshold is zero.

2022-09-27 22:30 UTC, uhafner requested changes
Thanks for your pull request, just a small improvement to the test would make sense.

2022-09-27 22:30 UTC, uhafner commented on plugin/src/test/java/io/jenkins/plugins/analysis/core/util/QualityGateEvaluatorTest.java
> +
Can you add a check that the log is empty?

2022-10-02 10:14 UTC, uhafner approved these changes
I hope you don't mind, in order to get this PR merged I added the missing assertion on my own 😄

2022-10-02 12:02 UTC, merged

2022-10-03 18:15 UTC, miked-rr commented
Of course I don't mind! Thanks!