Align Plugin Util Api version
jenkinsci/warnings-ng-plugin pull request #1425
Opened 2022-12-13 15:37 UTC by rsandell

Tests and hpi runtime was using different versions causing test compilation errors when running with PCT

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-12-13 22:03 UTC, uhafner requested changes

2022-12-13 22:03 UTC, uhafner commented on .gitignore
> +.idea
These files contain the coding style for this project, please revert

2022-12-13 22:03 UTC, uhafner commented on plugin/src/test/java/io/jenkins/plugins/analysis/warnings/PluginArchitectureTest.java
> +    static final ArchRule NO_PUBLIC_ARCHITECTURE_TESTS = ArchRuleDefinition.fields().that().areAnnotatedWith(ArchTest.class).should().notBePublic();
```suggestion
    static final ArchRule ONLY_PACKAGE_PRIVATE_ARCHITECTURE_TESTS = ArchitectureRules. ONLY_PACKAGE_PRIVATE_ARCHITECTURE_TESTS;
```

2022-12-14 11:23 UTC, rsandell commented on .gitignore
> +.idea
```suggestion

```

2022-12-14 12:53 UTC, uhafner requested changes

2022-12-14 12:53 UTC, uhafner commented on plugin/src/test/java/io/jenkins/plugins/analysis/warnings/PluginArchitectureTest.java
> +import com.tngtech.archunit.lang.syntax.ArchRuleDefinition;
```suggestion
```

2022-12-14 12:53 UTC, uhafner commented on plugin/src/test/java/io/jenkins/plugins/analysis/warnings/PluginArchitectureTest.java
> +    static final ArchRule ONLY_PACKAGE_PRIVATE_ARCHITECTURE_TESTS = ArchitectureRules. ONLY_PACKAGE_PRIVATE_ARCHITECTURE_TESTS;
```suggestion
    static final ArchRule ONLY_PACKAGE_PRIVATE_ARCHITECTURE_TESTS = ArchitectureRules.ONLY_PACKAGE_PRIVATE_ARCHITECTURE_TESTS;
```

2022-12-14 12:55 UTC, merged

2022-12-14 12:55 UTC, uhafner commented
Thanks!