[JENKINS-71435] Unknown category unusable in Java Compiler Warnings
jenkinsci/warnings-ng-plugin pull request #1648
Opened 2023-12-29 17:55 UTC by debayangg

Fixes [JENKINS-71435](https://issues.jenkins.io/browse/JENKINS-71435). Changed formatProperty() method in DetailsTableModel.java to display issues with blank categories as '-' category.

Before change:
![Before](https://github.com/jenkinsci/warnings-ng-plugin/assets/66942246/444321f2-3b5b-4a23-a233-71cc0bd97708)

After change:
![After](https://github.com/jenkinsci/warnings-ng-plugin/assets/66942246/d72fdb00-65f1-47ac-b750-dfffb69ed2ba)

### Testing done
![Tests Passed](https://github.com/jenkinsci/warnings-ng-plugin/assets/66942246/ba3d96df-8001-42cb-b50b-9f64f9e0882d)

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-12-29 21:39 UTC, uhafner requested changes
Can you please also add a small unit test in `DetailsTableModelTest`?

2023-12-29 22:40 UTC, debayangg commented
I will be travelling for a few days so it might take a bit of time to add the unit tests.

2024-01-02 13:57 UTC, debayangg commented
For the unit test I'm thinking of creating a new issue using IssueBuilder with an empty property and checking if the returned property is - or not. In this case I had a question, can I use the Message described in AbstractDetailsModelTest class for the created issue?

2024-01-04 15:34 UTC, uhafner approved these changes

2024-01-04 15:35 UTC, merged