Add document for warnings checks
jenkinsci/warnings-ng-plugin pull request #602
Opened 2020-08-28 11:24 UTC by XiongKezhi

2020-08-28 11:25 UTC, XiongKezhi commented
cc @timja

2020-08-28 11:59 UTC, timja approved these changes
LGTM

2020-08-28 11:59 UTC, timja commented on doc/Documentation.md
> +In order to disable the checks feature, set the property `skipPublishingChecks` to `true`, see the following example:
```suggestion
In order to disable the checks feature, set the property `skipPublishingChecks` to `true`:
```

2020-08-28 15:19 UTC, uhafner requested changes
Can you please add an additional sentence (and maybe image) that shows that additionally the status of the quality gate will be reflected in the status of the check?

2020-08-29 08:53 UTC, uhafner approved these changes
Thanks!

2020-08-29 08:53 UTC, merged